spring:
  application:
    name: dtkg3qob
  kafka:
    bootstrap-servers: rocket-01.srvs.cloudkafka.com:9094,rocket-02.srvs.cloudkafka.com:9094,rocket-03.srvs.cloudkafka.com:9094
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${USERNAME}" password="${PASSWORD}";
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.messagingstompwebsocket.dto
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cloud:
    function:
      definition: updateStorage;storageUpdated
    stream:
      kafka:
        streams:
          binder:
            functions:
              updateStorage:
                applicationId: dtkg3qob
              storageUpdated:
                applicationId: storage-updated-processor
      bindings:
        updateStorage-in-0:
          destination: dtkg3qob-events
        storageUpdated-in-0:
          destination: dtkg3qob-storage-reduce-sum-changelog
