// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/com/example/kafka/dto.proto

package com.example.kafka;

public interface DtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.kafka.Dto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 1;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
