// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/com/example/kafka/dto.proto

package com.example.kafka;

public final class DtoProto {
  private DtoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_kafka_Dto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_kafka_Dto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*src/main/proto/com/example/kafka/dto.p" +
      "roto\022\021com.example.kafka\"\024\n\003Dto\022\r\n\005value\030" +
      "\001 \001(\tB,\n\021com.example.kafkaB\010DtoProtoP\001Z\013" +
      "generatedpbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_kafka_Dto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_kafka_Dto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_kafka_Dto_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
